version: '2'
services:
    jhipsterapplication5-app:
        image: jhipsterapplication5
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterapplication5-mysql:3306/jhipsterapplication5?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipsterapplication5-elasticsearch:9300
        ports:
            - 8080:8080
    jhipsterapplication5-mysql:
        extends:
            file: mysql.yml
            service: jhipsterapplication5-mysql
    jhipsterapplication5-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsterapplication5-elasticsearch
